### ISSUE TITLE
请问练习题有没有答案参考

### ISSUE THREAD

**Issue by HenryWang628** [datawhalechina/team-learning-sql#1]
请问练习题有没有答案参考？谢谢

**Comment by mba1398** [comment]
练习题参考答案公布在 `Datawhale` 论坛了，网址如下：

1. [http://datawhale.club/t/topic/836](http://datawhale.club/t/topic/836)
2. [http://datawhale.club/t/topic/993](http://datawhale.club/t/topic/993)

有问题随时沟通。
