### ISSUE TITLE
sql语句如何恢复删掉的表

### ISSUE THREAD

**Issue by hchhtc123** [datawhalechina/team-learning-sql#3]
来自1.4 的练习题：
编写SQL语句来恢复删除掉的Addressbook表

小白想请教下大佬，要怎么恢复删掉的表，是使用drop删掉的。

**Comment by mba1398** [comment]
小白很难恢复删掉的表，所以要谨慎删除。
想要恢复的话，可以了解一下 `Flashback` 插件。
专业的DBA有办法恢复已删除的表，但是不属于本课程的教学范围。
另外，新项目地址为 [https://github.com/datawhalechina/wonderful-sql](https://github.com/datawhalechina/wonderful-sql)，欢迎关注。
